// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oyppokilrlhvjbuqebxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95cHBva2lscmxodmpidXFlYnh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NTYyOTYsImV4cCI6MjA3MTIzMjI5Nn0.4foNMoxAfBXxZ2fYwPEpw0OwittfALmwNXTZ_riqsDA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});